### ISSUE TITLE
Not working for iOS

### ISSUE THREAD

**Issue by theKashey** [davidtheclark/no-scroll#11]
`overflow:hidden` does not work on Mobile Safari as expected - it does not prevent scrolling.

The only way to prevent a scroll - is to prevent `touch` event.

**Comment by davidtheclark** [comment]
Yes, this is a known caveat. Known to *me*, at least — I thought it was written down in the README but I guess that's a false memory.

> The only way to prevent a scroll - is to prevent touch event.

The challenge here is preventing scroll on the document *only* — so you could still scroll in nested scrollable areas. I'd love to learn how this can be implemented!

**Comment by theKashey** [comment]
Easy:

- https://github.com/theKashey/react-locky/blob/master/src/handleScroll.js
- https://github.com/willmcpo/body-scroll-lock/blob/master/src/bodyScrollLock.js#L119
- https://github.com/jossmac/react-scrolllock/blob/master/src/utils.js#L18

**Comment by davidtheclark** [comment]
Added a note to the README in a426e8c03524ace7936eb7eab26461369d514705
