### ISSUE TITLE
Not working with IE11

### ISSUE THREAD

**Issue by brierel** [davidtheclark/no-scroll#2]
With Internet Explorer 11, off() function doesn't work.
Cause : the regular expression used can't work because IE returns a beautified value (a space is inserted after each ':') of style attribute when using doc.getAttribute('style').

**Comment by davidtheclark** [comment]
Thanks for reporting the bug! It made me learn a better way of setting inline styles.

**Comment by davidtheclark** [comment]
Released in 1.1.2. Let me know if anything else goes haywire.
