### ISSUE TITLE
Only allow turning off no-scroll if it is currently turned on

### ISSUE THREAD

**Issue by danoc** [davidtheclark/no-scroll#7]
Hello! 

It's fairly easy to misuse `no-scroll` and call `.off` before it has been turned on. When misused, this causes the page to scroll to the top since `scrollTop` will be undefined:

https://github.com/davidtheclark/no-scroll/blob/fcf54b6f521722894248119f22430c26e39fd394/index.js#L37-L46

Would it make sense to `return` immediately on L38 when `isOn` is false? Alternatively, don't run `window.scroll` if `scrollTop` is `undefined`? (Happy to submit a PR.)

Thanks, @davidtheclark! Your modal libraries are 💯.

**Comment by davidtheclark** [comment]
> Would it make sense to returning immediately on L38 when isOn is false?

This sounds good to me 👍I'll cut a quick release with a fix.

**Comment by davidtheclark** [comment]
Published in 2.1.1.
